namespace: ncstate
name: network
version: 1.1.0
readme: README.md
authors:
  - Matt Haught <dmhaught@ncsu.edu>
description: NC State University network collection
license_file: COPYING
tags: [ncstate, network]
dependencies:
  ansible.netcommon: '>=1.0.0'
  community.network: '>=1.0.0'
repository: https://github.com/haught/ncstate.network
documentation: https://github.com/haught/ncstate.network
homepage: https://github.com/haught/ncstate.network
issues: https://github.com/haught/ncstate.network/issues
